### ISSUE TITLE
Move css to a proper file

### ISSUE THREAD

**Issue by Sacules** [Sacules/chartsy#2]
Rename `collage.css` to `styles.css` and import it from the main App component instead.

**Comment by prakarsh7695** [comment]
Where do want the style.css file to be placed?

**Comment by Thusal06** [comment]
I'll like to work on it,

**Comment by Sacules** [comment]
Hi, I'm afraid this issue already has too many folks interested on it. If #4 doesn't show activity in the following days, I'll just merge #9.
