### ISSUE TITLE
Fix "null - null" when dragging and dropping an image from the chart to nowhere

### ISSUE THREAD

**Issue by Sacules** [Sacules/chartsy#21]
![image](https://user-images.githubusercontent.com/31902745/95757165-2e2bcd80-0c7d-11eb-821f-af55987adf28.png)

It turns the image into "null - null" - it's still replaceable, but it's still annoying. The image should go back to its original position and remain the same. The whole drag and drop logic is on `image.tsx`.

**Comment by Buffettt** [comment]
Hey :) I can help you with this if you want to :)

**Comment by Sacules** [comment]
Sure, give it a go :)

**Comment by Buffettt** [comment]
Hi I gave a merge request so please check if it's ok. I fixed a few things there. :)

**Comment by Buffettt** [comment]
It should be ok now :) check it please
