### ISSUE TITLE
Move state of search and results from the home component into its own component 

### ISSUE THREAD

**Issue by Sacules** [Sacules/chartsy#6]
Right now, as legacy of not having touched it for a while, there exists some state related to search that should be on its own component rather than in the home one.

**Comment by varunpappu** [comment]
@Sacules Can I pick this one up?

**Comment by Sacules** [comment]
Sure, go ahead :)

**Comment by varunpappu** [comment]
@Sacules Awesome. Can this be assigned to me. :D
