### ISSUE TITLE
Fix and remove @ts-ignore on forwardRef

### ISSUE THREAD

**Issue by Sacules** [Sacules/chartsy#7]
For some reason the compiler complains about the types when doing a forwardRef on the home component. The info given by Typescript is not very useful, so I've used the comment to ignore the warnings. Everything works fine, so it's likely just an type error I can't figure out.

**Comment by creativenull** [comment]
Hey there!

I can take a look at this. It seems like it's needs to be explicitly say `RefObject` when passing as props.

I can make a PR for this for you to review🙂.
